/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pja15_06042020;

import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Andi
 */
public class StudentRecord_View extends javax.swing.JFrame {

    /**
     * Creates new form StudentRecord_View
     */
    StudentRecord_Controller controller;
    
    public StudentRecord_View() {
        initComponents();
        controller = new StudentRecord_Controller(this);
        controller.clearForm();
        controller.viewTable();
    }

    public JTextField getjTF_Alamat() {
        return jTF_Alamat;
    }

    public JTextField getjTF_BahasaInggris() {
        return jTF_BahasaInggris;
    }

    public JTextField getjTF_IPA() {
        return jTF_IPA;
    }

    public JTextField getjTF_Matematika() {
        return jTF_Matematika;
    }

    public JTextField getjTF_Umur() {
        return jTF_Umur;
    }

    public JTextField getjTF_Nama() {
        return jTF_Nama;
    }

    public JTable getTableStudent() {
        return TableStudent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LB_StudentRecord = new javax.swing.JLabel();
        LB_Nama = new javax.swing.JLabel();
        LB_Alamat = new javax.swing.JLabel();
        LB_Umur = new javax.swing.JLabel();
        LB_Matematika = new javax.swing.JLabel();
        LB_Bing = new javax.swing.JLabel();
        LB_IPA = new javax.swing.JLabel();
        btnCancel = new javax.swing.JToggleButton();
        jTF_Nama = new javax.swing.JTextField();
        jTF_Alamat = new javax.swing.JTextField();
        jTF_Umur = new javax.swing.JTextField();
        jTF_Matematika = new javax.swing.JTextField();
        jTF_BahasaInggris = new javax.swing.JTextField();
        jTF_IPA = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableStudent = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LB_StudentRecord.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LB_StudentRecord.setText("Student Record");

        LB_Nama.setText("Nama");

        LB_Alamat.setText("Alamat");

        LB_Umur.setText("Umur");

        LB_Matematika.setText("Matematika");

        LB_Bing.setText("Bahasa Inggris");

        LB_IPA.setText("IPA");

        btnCancel.setText("cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jTF_Nama.setText("jTextField1");

        jTF_Alamat.setText("jTextField2");

        jTF_Umur.setText("jTextField3");

        jTF_Matematika.setText("jTextField4");

        jTF_BahasaInggris.setText("jTextField5");

        jTF_IPA.setText("jTextField6");

        TableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Umur", "Nilai"
            }
        ));
        TableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableStudent);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_Umur)
                            .addComponent(LB_Alamat)
                            .addComponent(LB_Nama)
                            .addComponent(LB_Matematika)
                            .addComponent(LB_Bing)
                            .addComponent(LB_IPA)
                            .addComponent(btnInsert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_BahasaInggris)
                            .addComponent(jTF_Alamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDel)
                                .addGap(64, 64, 64)
                                .addComponent(btnCancel))
                            .addComponent(jTF_Nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Matematika, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Umur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_IPA)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(LB_StudentRecord)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_StudentRecord)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_Nama)
                    .addComponent(jTF_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Alamat)
                    .addComponent(jTF_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_Umur)
                    .addComponent(jTF_Umur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_Matematika)
                    .addComponent(jTF_Matematika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_Bing)
                    .addComponent(jTF_BahasaInggris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_IPA)
                    .addComponent(jTF_IPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnInsert)
                    .addComponent(btnUpdate)
                    .addComponent(btnDel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        controller.clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void TableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStudentMouseClicked
        // TODO add your handling code here:
        controller.onClickTable();
    }//GEN-LAST:event_TableStudentMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.viewTable();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.viewTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.viewTable();
    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecord_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecord_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecord_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecord_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecord_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Alamat;
    private javax.swing.JLabel LB_Bing;
    private javax.swing.JLabel LB_IPA;
    private javax.swing.JLabel LB_Matematika;
    private javax.swing.JLabel LB_Nama;
    private javax.swing.JLabel LB_StudentRecord;
    private javax.swing.JLabel LB_Umur;
    private javax.swing.JTable TableStudent;
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_Alamat;
    private javax.swing.JTextField jTF_BahasaInggris;
    private javax.swing.JTextField jTF_IPA;
    private javax.swing.JTextField jTF_Matematika;
    private javax.swing.JTextField jTF_Nama;
    private javax.swing.JTextField jTF_Umur;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
